#!/bin/bash

LOGFILE="/var/log/zbx4jos.log"

.  /opt/sos-berlin.com/jobscheduler/OSSLUSER/bin/jobscheduler_environment_variables.sh
export Z4J_HOME="/home/OSSLUSER/zbx4jos"

cd $Z4J_HOME

cmd=$1

if [ "$cmd" == "" ]
then
	cmd="help"
fi

D=`date`
I=`id`
echo -n "[ $D ] : Access ID is $I : Command is $cmd $2 $3 $4 $5 $6 $7" >> $LOGFILE
fab $cmd 2>&1 | grep -v "Done." | tee -a $LOGFILE

#
